@[TOC](动手学深度学习笔记（一）：一些基础知识)
这是《动手学深度学习》（PyTorch版）（Dive-into-DL-PyTorch）的学习笔记，里面有一些代码是我自己拓展的

# 1 数据操作
## 1.1 创建Tensor

Tensor即张量，更适合深度学习，可以看作一个多维数组。
>标量：0维张量
>向量：1维张量
>矩阵：2维张量
### 1.1.1 创建未初始化的Tensor

In [2]:
import torch
x = torch.empty(5, 3)  #创建一个5行3列未初始化的Tensor
x

tensor([[1.0745e-38, 5.9694e-39, 8.9082e-39],
        [1.0194e-38, 9.1837e-39, 4.6837e-39],
        [9.9184e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38]])

In [6]:
a = torch.IntTensor(2, 3)
b = torch.FloatTensor(2, 3)

print(a)
print(b)

tensor([[ 926428514,  908931682,  808608560],
        [1630889059,  778254384, 1667594341]], dtype=torch.int32)
tensor([[1.0978e-05, 2.5808e-06, 6.4897e-10],
        [2.0913e+20, 5.1664e-11, 7.1450e+31]])


### 1.1.2 生成随机数

（1）均匀分布
torch.rand(sizes)：返回从区间 \[0, 1)的==均匀分布==中抽取的一组随机数；
torch.randint(low=0, high, size, out=None, dtype=None)：返回在[low , high)之间均匀生成的随机==整数==填充的张量，张量的形状由变量的参数大小来定义；
torch.randint_like(input, low=0, high, dtype=None)：返回与张量输入相同形状的张量，该张量由在 [low , high) 之间均匀生成的随机整数填充。

In [3]:
print(torch.rand(2, 3))  
x = torch.randint(1, 10, (2, 3))
print(x)
print(torch.randint_like(x, 11, 20))
#注意只有第一个是小数

tensor([[0.8665, 0.8670, 0.4948],
        [0.0677, 0.0676, 0.9548]])
tensor([[8, 7, 4],
        [9, 5, 6]])
tensor([[12, 16, 17],
        [11, 19, 12]])


（2）标准正态分布
torch.randn(siezs)：返回从**标准正态分布（均值为0，方差为1，即高斯白噪声）** 中抽取的一组随机数；
torch.randn_like(input, *, dtype=None)：返回与输入相同大小的张量，该张量由均值为0和方差为1的正态分布中的随机数填充。 

In [4]:
x = torch.randn(2, 3)
print(x)
print(torch.randn_like(x))

tensor([[-0.2736,  1.8607, -2.4172],
        [ 2.1359, -1.4494,  0.8359]])
tensor([[ 0.3606,  0.0375,  0.6035],
        [ 0.4650, -1.1317, -0.7926]])


（3）随机排列
torch.randperm(n)：返回一个从 0 到 n-1 的随机整数排列，不包含上边界。

In [5]:
print(torch.randperm(6)) 

tensor([2, 4, 5, 1, 0, 3])


（4）线性间距向量
torch.linespace(s,e,steps)：从s到e（左闭右闭，类似[s,e]），均匀切成steps份。

In [6]:
#torch.linspace(s,e,steps)：从s到e（左闭右闭，类似[s,e]），均匀切成steps份
print(torch.linspace(1, 9, 2))
print(torch.linspace(1, 9, 2).type())  #类型是浮点型
print(torch.linspace(1, 9, 3))
print(torch.linspace(1, 9, 4))
print(torch.linspace(1, 9, 5))
print(torch.linspace(1, 9, 6))

tensor([1., 9.])
torch.FloatTensor
tensor([1., 5., 9.])
tensor([1.0000, 3.6667, 6.3333, 9.0000])
tensor([1., 3., 5., 7., 9.])
tensor([1.0000, 2.6000, 4.2000, 5.8000, 7.4000, 9.0000])


（5）泊松分布
torch.poisson(input *, generator=None)：返回与输入相同大小的张量，从泊松分布中取样的每个元素都具有相应元素在输入中给定的速率参数。

In [7]:
#泊松分布：返回与输入相同大小的张量，从泊松分布中取样的每个元素都具有相应元素在输入中给定的速率参数
rates = torch.rand(3, 4) * 5  # rate parameter between 0 and 5
print(rates)
#rates为[0, 1)均匀分布的3×4矩阵，数值再×5，所以是在[0, 5)直接分布
print(torch.poisson(rates))

tensor([[2.4408, 3.7235, 3.7592, 1.4588],
        [1.2718, 0.9309, 3.2713, 4.3106],
        [2.5758, 3.2454, 1.0111, 3.8317]])
tensor([[1., 4., 4., 1.],
        [0., 1., 6., 2.],
        [2., 5., 0., 7.]])


### 1.1.3 torch.Tensor()与torch.tensor()

In [8]:
x = torch.Tensor(5, 3)  #这里是torch.Tensor(*size)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.1020e-38],
        [1.0102e-38, 1.0745e-38, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [9]:
x = torch.tensor([[1,2,3], [4,5,6]])  #直接根据数值创建，这里是torch.Tensor(*data)
print(x)
print(x.type())  #注意不能用type(x)，否则出来的只会是<class 'torch.Tensor'>

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.LongTensor


In [10]:
x = torch.Tensor([[1,2,3], [4,5,6]])
print(x)
print(x.type())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.FloatTensor


注意 **torch.Tensor()和torch.tensor()** 之间的区别：

（1）torch.Tensor()是Python类，更明确的说，是默认张量类型torch.FloatTensor()的别名，上面会调用Tensor类的构造函数__init__，生成单精度浮点类型的张量；

（2）torch.tensor()仅仅是Python的函数，函数原型是：
>torch.tensor(data, dtype=None, device=None, requires_grad=False)

其中data可以是：list, tuple, NumPy ndarray, scalar和其他类型。
torch.tensor会从data中的数据部分做拷贝（而不是直接引用），根据原始数据类型生成相应的torch.LongTensor、torch.FloatTensor和torch.DoubleTensor。

### 1.1.4 一些特殊值矩阵

In [11]:
x = torch.zeros(2, 5, 3)  #创建2个5行3列、值为0的Tensor
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [12]:
x = torch.zeros(5, 3, dtype=torch.long)  #创建一个5行3列长整型、值为0的Tensor
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


dtype=torch.long表示创建的是长整型，同理，后面出现的dtype=torch.float就是类型改为浮点数
dtype=torch.double与后面的dtype=torch.float64相同

In [13]:
x = x.new_ones(5, 3, dtype=torch.float64)  
#通过现有的Tensor创建,此时返回的Tensor默认具有相同的数据类型，新的张量将会重用已有张量的属性（此处还没怎么弄懂）
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x = torch.zeros(5, 3, dtype=torch.double)  #上面的值为0的
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [15]:
print(torch.ones(5, 3))  #全1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [16]:
print(torch.eye(5, 3))  #对角线为1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
#torch.arange(s,e,step)：从s到e（左闭右开，类似[s,e)），步长为step
print(torch.arange(1, 9))
print(torch.arange(1, 9).type())  #类型是长整型
print(torch.arange(1, 9, 2))
print(torch.arange(1, 10, 2))

tensor([1, 2, 3, 4, 5, 6, 7, 8])
torch.LongTensor
tensor([1, 3, 5, 7])
tensor([1, 3, 5, 7, 9])


In [18]:
#normal(mean,std)：正态分布，（均值，标准差）
mean = torch.arange(1., 11.)
std = torch.arange(1, 0, -0.1)
x = torch.normal(mean, std)
print(mean)
print(std)
print(x)  #每一次编译，x的值都会发生变化

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000])
tensor([ 0.9868,  2.1501,  3.3277,  3.9642,  5.6998,  6.5027,  7.1676,  8.2045,
         9.1502, 10.0952])


In [19]:
#获取Tensor形状：
print(x.size())
print(x.shape)
print(x.numel())  #张量中元素的总数

torch.Size([10])
torch.Size([10])
10


## 1.2 操作
### 1.2.1 算术操作
加减乘除、求余、求幂、指数、绝对值：

In [28]:
#可以是两个张量，也可以是张量和数字
x = torch.tensor([1, 2, 4])
y = torch.tensor([2, 1, 2])
print(x + y, torch.add(x, y), x.add(y))
print(x - y)
print(torch.abs(x - y))  #绝对值
print(x * y, torch.mul(x, y), x.mul(y))
print(x / y, torch.div(x, y), x.div(y))
print(x % y) 
print(x ** y, torch.pow(x, y), x.pow(y))
print(torch.exp(x))

tensor([3, 3, 6]) tensor([3, 3, 6]) tensor([3, 3, 6])
tensor([-1,  1,  2])
tensor([1, 1, 2])
tensor([2, 2, 8]) tensor([2, 2, 8]) tensor([2, 2, 8])
tensor([0.5000, 2.0000, 2.0000]) tensor([0.5000, 2.0000, 2.0000]) tensor([0.5000, 2.0000, 2.0000])
tensor([1, 0, 0])
tensor([ 1,  2, 16]) tensor([ 1,  2, 16]) tensor([ 1,  2, 16])
tensor([ 2.7183,  7.3891, 54.5981])


多种加法：

In [125]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[3, 2, 1], [6, 5, 4], [9, 8, 7]])

print(x + y)

print(torch.add(x, y))

result = torch.empty(3, 3)
torch.add(x, y, out=result) #把x+y放入创建的空tensor中
print(result)
print(result.type())

y.add_(x)  #上面的一种变式，注意有一个‘_’，这个符号在所有替换自身操作符的末尾都有，另外，输出的方式还可以象python一样。
print(y)
print(y.type())

tensor([[ 4,  4,  4],
        [10, 10, 10],
        [16, 16, 16]])
tensor([[ 4,  4,  4],
        [10, 10, 10],
        [16, 16, 16]])
tensor([[ 4.,  4.,  4.],
        [10., 10., 10.],
        [16., 16., 16.]])
torch.FloatTensor
tensor([[ 4,  4,  4],
        [10, 10, 10],
        [16, 16, 16]])
torch.LongTensor


In [23]:
#矩阵乘法
x = torch.tensor([[1, 2]])  #要确保是矩阵
y = torch.tensor([[3], [4]])
torch.mm(x, y), x.mm(y)  #1*3+2*4

(tensor([[11]]), tensor([[11]]))

In [24]:
#矩阵乘向量
x = torch.tensor([[1,2,3], 
                  [4,5,6]])
y = torch.tensor([1,2,3])  #列向量
torch.mv(x, y), x.mv(y)  #就和矩阵相乘的方式一样

(tensor([14, 32]), tensor([14, 32]))

注意出现的结果的类型！第三个结果的类型是浮点型。

### 1.2.2 索引
裁剪

In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.clamp(x, 2, 7)  #对x进行在2和7之间的裁剪

tensor([[2, 2, 3],
        [4, 5, 6],
        [7, 7, 7]])

x[行切片,列切片]

In [151]:
x = torch.tensor([[1,2,3,4], [3,4,5,6], [0,9,0,1], [8,2,1,3]])
print(x)

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [0, 9, 0, 1],
        [8, 2, 1, 3]])


In [152]:
print(x[1:,])  #逗号前面是行切片，索引为1的行开始切片到最后，当对列没有修改时，逗号可省略。x[1:]=x[1:,]=x[1:,:]

tensor([[3, 4, 5, 6],
        [0, 9, 0, 1],
        [8, 2, 1, 3]])


In [153]:
print(x[1:3,])  #只切片索引为1的行

tensor([[3, 4, 5, 6],
        [0, 9, 0, 1]])


In [154]:
print(x[1:3,1:3])  #切片索引为1、2和行和列

tensor([[4, 5],
        [9, 0]])


In [155]:
print(x[:,1:3])  #但是这里如果是x[,1:3]会报错

tensor([[2, 3],
        [4, 5],
        [9, 0],
        [2, 1]])


In [156]:
print(x[::2, ::3])  #跳着访问，第0行和第2行，第0列和第3列

tensor([[1, 4],
        [0, 1]])


In [158]:
print(x[-1])  #可以用负索引

tensor([8, 2, 1, 3])


In [161]:
x[1, 2] = 10  #根据索引更改
print(x)
x[0:2, :] = 12
print(x)

tensor([[ 1,  2,  3,  4],
        [ 3,  4, 10,  6],
        [ 0,  9,  0,  1],
        [ 8,  2,  1,  3]])
tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 0,  9,  0,  1],
        [ 8,  2,  1,  3]])


可以用切片来修改：

In [111]:
x = torch.tensor([[1,2,3,4], [3,4,5,6], [0,9,0,1], [8,2,1,3]])
y = x[0,]
print(x)
print(y)

y += 10
print(y)
print(x[0])  

x[0] -= 5
print(x[0])
print(y)

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [0, 9, 0, 1],
        [8, 2, 1, 3]])
tensor([1, 2, 3, 4])
tensor([11, 12, 13, 14])
tensor([11, 12, 13, 14])
tensor([6, 7, 8, 9])
tensor([6, 7, 8, 9])


- 这里需要注意！！！索引出来的结果与原数据内存共享，修改了一个，另一个也修改，所以后面的结果是同步的

PyTorch还提供了一些高级的选择函数：

In [87]:
#index_select(input, dim, index)：在指定维度dim上选取（dim=0，按行选取；dim=1，按列选取），index是索引的序号。
x = torch.tensor([[1,2,3,4], [3,4,5,6], [0,9,0,1], [8,2,1,3]])
print(x)
y = torch.index_select(x, 0, torch.tensor([0, 2]))  #按行选取，索引第0行和第2行
print(y)
z = torch.index_select(x, 1, torch.tensor(1))  #按列选取，第1列
print(z)

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [0, 9, 0, 1],
        [8, 2, 1, 3]])
tensor([[1, 2, 3, 4],
        [0, 9, 0, 1]])
tensor([[2],
        [4],
        [9],
        [2]])


In [88]:
#masked_select(input, mask)：mask取出的是布尔值索引（掩码）（即真为1，假为0），然后根据取出的非0掩码从中取值
x = torch.tensor([[0,2,4], [1,3,5]])
print(x)
y = torch.masked_select(x, x<5)  #x<5时，布尔值索引是[1,1,1,1,1,0]，所以取出[0, 2, 4, 1, 3]
print(y)

tensor([[0, 2, 4],
        [1, 3, 5]])
tensor([0, 2, 4, 1, 3])


In [89]:
#nonzero(input)：取出非0元素的下标
x = torch.tensor([[0,2,4], [1,0,5]])
print(torch.nonzero(x))

tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 2]])


In [90]:
#gather(input, dim, index)：根据index，在dim维度上选取数据，输出的size与index一样
x = torch.tensor([[0,2,4], [1,3,5], [2,1,0]])
print(x)
index = torch.tensor([[2,0], [1,2], [0,1]])
print(index)

a = torch.gather(x, 0, index)
b = torch.gather(x, 1, index)
print(a)
print(b)

tensor([[0, 2, 4],
        [1, 3, 5],
        [2, 1, 0]])
tensor([[2, 0],
        [1, 2],
        [0, 1]])
tensor([[2, 2],
        [1, 1],
        [0, 3]])
tensor([[4, 0],
        [3, 5],
        [2, 1]])


a中，dim=0，表示在行上取数据。那么就以列作为取值的基准。index中第一列的[2,1,0]表示a的第0列是x的第0列中，行号为[2,1,0]的数，以此类推。
由于index只有两列，所以a的结果不涉及x的第3列。

b中，dim=1，表示在列上取数据。那么就以行作为取值的基准。index中第一行的[2,0]表示b的第0行是x的第0行中，列号为[2,0]的数，以此类推。

### 1.2.3 改变形状
用view()或者reshape()来改变Tensor的形状：

In [137]:
x = torch.tensor([[0,2,4], [1,3,5]])
print(x, x.size())

a = x.view(6)
print(a, a.size())

b = x.view(1, 6)  #注意这就是两个维度了
print(b, b.size())

c = x.view(6, 1)
print(c, c.size())

d = x.reshape(3, 2)
print(d, d.size())

d = x.view(3, -1)
print(d, d.size())

tensor([[0, 2, 4],
        [1, 3, 5]]) torch.Size([2, 3])
tensor([0, 2, 4, 1, 3, 5]) torch.Size([6])
tensor([[0, 2, 4, 1, 3, 5]]) torch.Size([1, 6])
tensor([[0],
        [2],
        [4],
        [1],
        [3],
        [5]]) torch.Size([6, 1])
tensor([[0, 2],
        [4, 1],
        [3, 5]]) torch.Size([3, 2])
tensor([[0, 2],
        [4, 1],
        [3, 5]]) torch.Size([3, 2])


张量在给出其他部分后可以自动计算出一个维度。比如d = x.view(3, 2)就可以用d = x.view(3, -1)代替，结果一样。

view仅仅是改变了对这个张量的观察角度，内部数据并未改变。
即，x改变时，后面的abcd的数据都会随之改变。
如果希望不共享data内存，可以先用clone创造一个副本然后再使用view：

In [92]:
x_cp = x.clone().view(6)
print(x, x_cp)
x -= 1
print(x, x_cp)

tensor([[0, 2, 4],
        [1, 3, 5]]) tensor([0, 2, 4, 1, 3, 5])
tensor([[-1,  1,  3],
        [ 0,  2,  4]]) tensor([0, 2, 4, 1, 3, 5])


从结果可以看出：x减少了1，但是x_cp并没有变。
另外一个常用的函数就是item(), 它可以将一个标量Tensor转换成一个Python number：

In [93]:
x = torch.tensor([1.2345678])
print(x)
print(x.item())

tensor([1.2346])
1.2345677614212036


### 1.2.4 一些简单的矩阵操作

In [94]:
x = torch.tensor([[0,2,4,5], [1,3,5,2], [7,8,9,6]])
print(x)
print(x.trace())  #矩阵的迹（对角线之和）
print(x.diag())  #对角线元素
print(x.triu())  #上三角
print(x.tril())  #下三角
print(x.t())  #转置

tensor([[0, 2, 4, 5],
        [1, 3, 5, 2],
        [7, 8, 9, 6]])
tensor(12)
tensor([0, 3, 9])
tensor([[0, 2, 4, 5],
        [0, 3, 5, 2],
        [0, 0, 9, 6]])
tensor([[0, 0, 0, 0],
        [1, 3, 0, 0],
        [7, 8, 9, 0]])
tensor([[0, 1, 7],
        [2, 3, 8],
        [4, 5, 9],
        [5, 2, 6]])


### 1.2.5 把多个张量连结（concatenate）在一起

In [146]:
x = torch.arange(12).view((3, 4))
print(x)
y = torch.tensor([[2,1,4,3], [1,2,3,4], [5,6,7,8]])
print(y)

print(torch.cat((x, y), dim=0))  #按行连结
print(torch.cat((x, y), dim=1))  #按列连结

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]])
tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  5,  6,  7,  8]])


### 1.2.6 通过逻辑运算符构建二维张量

In [147]:
print(x == y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


### 1.2.7 求和
对张量中的所有元素进行求和会产生一个只有一个元素的张量。

In [148]:
print(x.sum())

tensor(66)


## 1.3 广播机制
当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。

In [95]:
x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2], [3]])
print(x + y)

tensor([[2, 3],
        [3, 4],
        [4, 5]])


x中第一行的2个元素被广播（复制）到了第二行和第三行，而y中第一列的3个元素被广播（复制）到了第二列。如此，就可以对2个3行2列的矩阵按元素相加。即：

In [149]:
x = torch.tensor([[1, 2], [1, 2], [1, 2]])
y = torch.tensor([[1, 1], [2, 2], [3, 3]])
print(x + y)

tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 1.4 运算的内存开销
索引操作是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。

In [163]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


如果想指定结果到原来的y的内存，我们可以使用前面介绍的索引来进行替换操作：

In [164]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [165]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

True


上面是通过索引替换到y，或者也可以引入一个新的矩阵z：

In [166]:
z = torch.zeros_like(y)  #表示z的数值全为0，但是z的形状和数据类型与y相同
z_before = id(z)
z[:] = x + y
print(z_before == id(z))

True


对于view()，虽然view返回的Tensor与源Tensor是共享data的，但是依然是一个新的Tensor（因为Tensor除了包含data外还有一些其他属性），二者id（内存地址）并不一致。

## 1.5 Tensor和NumPy相互转换
### 1.5.1 Tensor转NumPy

In [167]:
a = torch.ones(5)
b = a.numpy()
print(type(a), type(b))  #a是Tensor，b是numpy
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### 1.5.2 Numpy转Tensor

In [169]:
c = torch.from_numpy(b)
print(b, c)

b += 1
print(b, c)

c += 1
print(b, c)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.])
[4. 4. 4. 4. 4.] tensor([4., 4., 4., 4., 4.])
[5. 5. 5. 5. 5.] tensor([5., 5., 5., 5., 5.])


In [100]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


- 所有在CPU上的Tensor（除了CharTensor）都支持与NumPy数组相互转换。
- 用numpy()和from_numpy()将Tensor和NumPy中的数组相互转换。
- 但是需要注意的一点是：这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！

### 1.5.3 直接用torch.tensor()将NumPy数组转换成Tensor
该方法总是会进行数据拷贝，返回的Tensor和原来的数据不再共享内存。

In [101]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 1.6 将大小为1的张量转换为Python标量

In [171]:
x = torch.tensor([3.5])
print(x, x.item(), float(a))

tensor([3.5000]) 3.5 3.5 3
